# Generated by Django 5.0.9 on 2024-12-05 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='organisation',
            table='organisation',
        ),
    ]
