# Generated by Django 5.0.9 on 2024-12-10 20:18

import django.db.models.deletion
import user_service.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0002_alter_organisation_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='name',
            field=models.CharField(max_length=125, validators=[user_service.validators.OrgModelValidator.name_validator]),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='user_service.user', validators=[user_service.validators.OrgModelValidator.owner_validator]),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=125, validators=[user_service.validators.RoleModelValidator.name_validator]),
        ),
        migrations.AlterField(
            model_name='user',
            name='organisation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_org', to='user_service.organisation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text='A secure password with at least one special character, uppercase letter, and number.', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_role', to='user_service.role', validators=[user_service.validators.UserModelValidator.role_validator]),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_station',
            field=models.CharField(choices=[('WH', 'warehouse'), ('SP', 'shop')], max_length=2, validators=[user_service.validators.UserModelValidator.user_station_validator]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Your unique username for CentaIMS', max_length=128, unique=True, validators=[user_service.validators.UserModelValidator.username_validator]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_service.user', validators=[user_service.validators.UserProfileValidator.user_validator]),
        ),
        migrations.AlterModelTable(
            name='organisation',
            table='organisations',
        ),
    ]
